name: 🚀 Release Deployer
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Run release-please to manage releases
      - name: Run release-please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: manifest
          default-branch: master

      # Step 2: Run Custom Deployer Action if releases are created
      - name: Run Custom Deployer Action
        if: ${{ steps.release.outputs.releases_created }}
        uses: devuri/rdx-release-deployer-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-path: ${{ secrets.DEPLOY_PATH }}
          deploy-host: ${{ secrets.DEPLOY_HOST }}
          deploy-port: ${{ secrets.DEPLOY_PORT }}
          deploy-user: ${{ secrets.DEPLOY_USER }}
          deploy-key: ${{ secrets.DEPLOY_KEY }}
          path: build/trunk/
          tag-name: ${{ steps.release.outputs.tag_name }}
          switches: '-avzr --exclude="*.env" --exclude="env" --exclude=".github" --exclude=".git" --exclude=".gitignore" --exclude=".user.ini"'
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          slack-channel: general
          slack-title: "Web Application Deployed"
          slack-message: "Deployment process completed."
          slack-username: "WebApp Deploy Bot"
          slack-footer: "Web Application Update Status"
