name: 🚀 Release & Deployment Workflow

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Generate Release with release-please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: manifest
          default-branch: main

      - name: 🚀 Deploy Release to Remote Server
        if: ${{ steps.release.outputs.releases_created }}
        uses: devuri/rdx-release-deployer-action@v1
        with:
          site-url: ${{ secrets.SITE_URL }}                 # 🌐 Deployment site URL
          github-token: ${{ secrets.GITHUB_TOKEN }}         # 🔑 GitHub Token
          deploy-path: ${{ secrets.DEPLOY_PATH }}           # 📂 Remote deployment path
          deploy-host: ${{ secrets.DEPLOY_HOST }}           # 🖥️ Remote deployment host
          deploy-port: ${{ secrets.DEPLOY_PORT }}           # 🔌 Remote deployment port
          deploy-user: ${{ secrets.DEPLOY_USER }}           # 👤 Remote deployment user
          deploy-key: ${{ secrets.DEPLOY_KEY }}             # 🔑 Remote deployment key
          tag-name: ${{ steps.release.outputs.tag_name }}   # 🏷️ Release tag name

          path: build/trunk/                                # 📁 Local build directory
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}       # 🔔 Slack webhook for notifications

